### ISSUE TITLE
test/none.rb : NoMatchingPatternError

### ISSUE THREAD

**Issue by naitoh** [k0kubun/ruby-jit-challenge#1]
I tried it with Docker Desktop 4.19.0 on m1 MacBook Air and got NoMatchingPatternError.

```
$ docker run -it -v "$(pwd):/app" k0kubun/rjit bash
Unable to find image 'k0kubun/rjit:latest' locally
latest: Pulling from k0kubun/rjit
2ab09b027e7f: Pull complete 
842035595284: Pull complete 
790b225fd068: Pull complete 
363c9fe91db1: Pull complete 
Digest: sha256:e5ae366399a9fda1d8d5b2e9093d8a1d796009c640a631b96e852afb16b2559b
Status: Downloaded newer image for k0kubun/rjit:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@4154b183a57b:/app# uname -a
Linux 4154b183a57b 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@4154b183a57b:/app# bin/ruby -v
ruby 3.3.0dev (2023-04-27T21:27:51Z master f2c367734f) +RJIT [x86_64-linux]
root@4154b183a57b:/app# bin/ruby test/none.rb
/app/lib/jit/compiler.rb:32:in `compile': :putnil: :nop === :putnil does not return true (NoMatchingPatternError)
	from /app/lib/jit.rb:10:in `compile'
	from test/none.rb:1:in `none'
	from test/none.rb:7:in `<main>'
```

Is the above the behavior you expect?

**Comment by k0kubun** [comment]
Yes, it's part of the challenge to add cases to fix the error. See "Compiling putnil" for details.

**Comment by naitoh** [comment]
OK, I see.

Thanks!
